# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andon Response
email: contact@andonresponse.com
description: > # this means to ignore newlines until "baseurl:"
  Andon Response is used for recording and analyzing abnormalities
  within a lean company. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andonresponse.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
